# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="eastwood"
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)

# Example format: plugins=(rails git textmate ruby lighthouse)a


plugins=(git python pip compleat  extract brew github autojump zsh-functional)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:$HOME/.monalisa/bin:$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/Users/knight/code/go/bin/


# alias for reload zshrc
alias reload!='. ~/.zshrc'

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

export EDITOR=vim

export PATH=$PATH:$(brew --prefix)/share/npm/bin

k(){ack "$*" --color}
k!(){ack "$*" --color | less -R}
sizeof(){du -h "$*"}
alias json='python -mjson.tool | pygmentize -l json'
alias todo='~/.todo'

PYTHONPATH="/usr/local/lib/python2.7/site-packages/:$PYTHONPATH"
export PYTHONPATH
#. ~/dotfiles/powerline/powerline/bindings/zsh/powerline.zsh
export GOPATH="/Users/knight/code/go"
export GOROOT="/usr/local/opt/go/libexec/"

export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/Cellar/openssl/1.0.1i/lib/"

export AUTOJUMP_AUTOCOMPLETE_CMDS='cp vim'
export PLAN9=/usr/bin/plan9port
export PATH=$PATH:$PLAN9/bin
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home"

source /Users/knight/.iterm2_shell_integration.zsh
